In [1]:
import numpy as np

In [2]:
a = np.zeros((3,2))
print(a)
print(len(a),len(a[0]))

[[0. 0.]
 [0. 0.]
 [0. 0.]]
3 2


In [3]:
b = np.zeros(shape=(2,3))
print(b)
print(np.shape(b))

[[0. 0. 0.]
 [0. 0. 0.]]
(2, 3)


In [4]:
c = np.array([[1,2],[3,4],[5,6]])
c

array([[1, 2],
       [3, 4],
       [5, 6]])

In [5]:
d = np.arange(np.shape(c)[0])
print(d)
np.random.shuffle(d)
print(d)

[0 1 2]
[0 2 1]


In [6]:
print(c)

[[1 2]
 [3 4]
 [5 6]]


In [7]:
print(c[d])

[[1 2]
 [5 6]
 [3 4]]


# Product Review and Sentiment Analysis

## objective

- Make the complete analysis: calculate the analysis accuracy

- Use the attribute of classes

- Make the charts

## Problem 1. runAnalysis

- Complete the if-then statements to count the accuracy of analysis

## Problem 2. runWholeAnalysis

- Complete the for loop and the related codes to run the analysis for the entire testing set

## Problem 3. runExperiments

- Complete the for loop to calculate the averages and the standard deviations



In [9]:
[i*30 for i in range(6)]

[0, 30, 60, 90, 120, 150]